Criei uma pasta para a disciplina com as seguintes pastas dentro:
- scripts
     Local onde estou colocando este código
- inputs
     1. Baixei o arquivo ccidRAW0.xls do moodle
     2. Abri no excel e salvei como .csv
     3. Coloquei o arquivo .csv na pasta "inputs"
- outputs
- figures

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import os

In [13]:
#Definindo caminho dos arquivos (fiz de um jeito que deve funcionar no computador de todos)
repopath = Path.cwd().parent
figure_path = os.path.join(repopath,'figures')
input_path = os.path.join(repopath,'inputs')
output_path = os.path.join(repopath,'outputs')

# 1. Tratamento preliminar dos dados

1) Importação dos dados

In [55]:
#Leitura do arquivo
df = pd.read_csv(os.path.join(input_path,'ccidRAW0.csv'),encoding='latin1')
df.columns = df.columns.str.strip() # Limpeza pois algumas colunas vem com espaços desnecessários e geraram erros
df

,localidade,dia juliano,ano,mês,TMP_CD,SAL_PSU,NH4_MGN,NO3_MGN,NO2_MGN,PT_MGP,PO4_MGP,DQO,DBO,CHLA_MGC,FLR
0,1,31519,1986,4,11.86,33.70,0.132222,0.045161,0.015217,0.100,NaN,44.0,5.0,0.265776,26.60
1,1,31548,1986,5,20.32,30.86,0.077780,0.045161,0.015217,0.100,NaN,51.0,5.0,0.197008,20.40
2,1,31576,1986,6,20.25,29.60,0.217778,NaN,0.015217,0.370,0.040000,26.0,5.0,0.007840,16.80
3,1,31607,1986,7,23.47,32.33,0.140000,0.045161,0.030435,0.100,NaN,33.0,5.0,0.255136,29.11
4,1,31637,1986,8,27.08,33.55,0.093333,0.022581,0.030435,0.180,NaN,43.0,3.2,0.154112,20.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,13,33098,1990,8,25.72,34.57,0.224000,0.011290,0.015217,0.600,0.019333,6.0,2.9,0.316848,77.60
680,13,33127,1990,9,23.08,34.72,0.192889,0.011290,0.015217,0.100,0.025333,29.0,1.9,0.073808,66.80
681,13,33157,1990,10,18.74,32.82,0.179667,0.011290,0.015217,0.042,0.002333,62.0,2.7,0.062160,51.70
682,13,33186,1990,11,11.86,32.31,0.059111,0.036355,0.015217,0.016,0.005000,52.0,2.6,0.050512,52.50
683,13,33218,1990,12,8.32,32.18,0.105000,0.050355,0.015217,0.044,0.003000,5.0,2.9,0.012432,42.40

2) Formatação das variáveis

In [56]:
df.info()
#Todas as variáveis estão sendo lidas da maneira correta.

<class 'pandas.DataFrame'>
RangeIndex: 684 entries, 0 to 683
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   localidade   684 non-null    int64
 1   dia juliano  684 non-null    int64
 2   ano          684 non-null    int64
 3   mês          684 non-null    int64
 4   TMP_CD       675 non-null    float64
 5   SAL_PSU      674 non-null    float64
 6   NH4_MGN      679 non-null    float64
 7   NO3_MGN      678 non-null    float64
 8   NO2_MGN      669 non-null    float64
 9   PT_MGP       665 non-null    float64
 10  PO4_MGP      410 non-null    float64
 11  DQO          679 non-null    float64
 12  DBO          679 non-null    float64
 13  CHLA_MGC     655 non-null    float64
 14  FLR          675 non-null    float64
dtypes: float64(11), int64(4)
memory usage: 80.3 KB

3. Criação das novas variáveis

In [57]:
#vou substituir os NaN por zero e depois substituir os zeros por NaN.
#Para isso, vou primeiro verificar se não tem zeros 

colunas_numericas = ['TMP_CD','SAL_PSU','NH4_MGN','NO3_MGN','NO2_MGN','PT_MGP','PO4_MGP','DQO','DBO','CHLA_MGC','FLR']

print('Contagem de zeros por coluna numérica:')
print((df[colunas_numericas] == 0).sum())

print('Contagem de NaN por coluna numérica:')
print((df[colunas_numericas].isna()).sum())

# Como não tem zeros, vou substituir os NaN por zeros tranquilamente

Contagem de zeros por coluna numérica:
TMP_CD      0
SAL_PSU     0
NH4_MGN     0
NO3_MGN     0
NO2_MGN     0
PT_MGP      0
PO4_MGP     0
DQO         0
DBO         0
CHLA_MGC    0
FLR         0
dtype: int64
Contagem de NaN por coluna numérica:
TMP_CD        9
SAL_PSU      10
NH4_MGN       5
NO3_MGN       6
NO2_MGN      15
PT_MGP       19
PO4_MGP     274
DQO           5
DBO           5
CHLA_MGC     29
FLR           9
dtype: int64

In [58]:
#transformando os NaN em zero e contanto de novo
df[colunas_numericas] = df[colunas_numericas].fillna(0)

print('Contagem de zeros por coluna numérica:')
print((df[colunas_numericas] == 0).sum())

print('Contagem de NaN por coluna numérica:')
print((df[colunas_numericas].isna()).sum())

Contagem de zeros por coluna numérica:
TMP_CD        9
SAL_PSU      10
NH4_MGN       5
NO3_MGN       6
NO2_MGN      15
PT_MGP       19
PO4_MGP     274
DQO           5
DBO           5
CHLA_MGC     29
FLR           9
dtype: int64
Contagem de NaN por coluna numérica:
TMP_CD      0
SAL_PSU     0
NH4_MGN     0
NO3_MGN     0
NO2_MGN     0
PT_MGP      0
PO4_MGP     0
DQO         0
DBO         0
CHLA_MGC    0
FLR         0
dtype: int64

3a) NOx = NO2 + NO3

In [60]:
df['NOx'] = df['NO2_MGN'] + df['NO3_MGN']
df

,localidade,dia juliano,ano,mês,TMP_CD,SAL_PSU,NH4_MGN,NO3_MGN,NO2_MGN,PT_MGP,PO4_MGP,DQO,DBO,CHLA_MGC,FLR,NOx
0,1,31519,1986,4,11.86,33.70,0.132222,0.045161,0.015217,0.100,0.000000,44.0,5.0,0.265776,26.60,0.060379
1,1,31548,1986,5,20.32,30.86,0.077780,0.045161,0.015217,0.100,0.000000,51.0,5.0,0.197008,20.40,0.060379
2,1,31576,1986,6,20.25,29.60,0.217778,0.000000,0.015217,0.370,0.040000,26.0,5.0,0.007840,16.80,0.015217
3,1,31607,1986,7,23.47,32.33,0.140000,0.045161,0.030435,0.100,0.000000,33.0,5.0,0.255136,29.11,0.075596
4,1,31637,1986,8,27.08,33.55,0.093333,0.022581,0.030435,0.180,0.000000,43.0,3.2,0.154112,20.20,0.053015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,13,33098,1990,8,25.72,34.57,0.224000,0.011290,0.015217,0.600,0.019333,6.0,2.9,0.316848,77.60,0.026508
680,13,33127,1990,9,23.08,34.72,0.192889,0.011290,0.015217,0.100,0.025333,29.0,1.9,0.073808,66.80,0.026508
681,13,33157,1990,10,18.74,32.82,0.179667,0.011290,0.015217,0.042,0.002333,62.0,2.7,0.062160,51.70,0.026508
682,13,33186,1990,11,11.86,32.31,0.059111,0.036355,0.015217,0.016,0.005000,52.0,2.6,0.050512,52.50,0.051572
683,13,33218,1990,12,8.32,32.18,0.105000,0.050355,0.015217,0.044,0.003000,5.0,2.9,0.012432,42.40,0.065572

3b) Ntot = NO2 + NO3 + NH4

In [61]:
df['Ntot'] = df['NO2_MGN'] + df['NO3_MGN'] + df['NH4_MGN']
df

,localidade,dia juliano,ano,mês,TMP_CD,SAL_PSU,NH4_MGN,NO3_MGN,NO2_MGN,PT_MGP,PO4_MGP,DQO,DBO,CHLA_MGC,FLR,NOx,Ntot
0,1,31519,1986,4,11.86,33.70,0.132222,0.045161,0.015217,0.100,0.000000,44.0,5.0,0.265776,26.60,0.060379,0.192601
1,1,31548,1986,5,20.32,30.86,0.077780,0.045161,0.015217,0.100,0.000000,51.0,5.0,0.197008,20.40,0.060379,0.138159
2,1,31576,1986,6,20.25,29.60,0.217778,0.000000,0.015217,0.370,0.040000,26.0,5.0,0.007840,16.80,0.015217,0.232995
3,1,31607,1986,7,23.47,32.33,0.140000,0.045161,0.030435,0.100,0.000000,33.0,5.0,0.255136,29.11,0.075596,0.215596
4,1,31637,1986,8,27.08,33.55,0.093333,0.022581,0.030435,0.180,0.000000,43.0,3.2,0.154112,20.20,0.053015,0.146349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,13,33098,1990,8,25.72,34.57,0.224000,0.011290,0.015217,0.600,0.019333,6.0,2.9,0.316848,77.60,0.026508,0.250508
680,13,33127,1990,9,23.08,34.72,0.192889,0.011290,0.015217,0.100,0.025333,29.0,1.9,0.073808,66.80,0.026508,0.219397
681,13,33157,1990,10,18.74,32.82,0.179667,0.011290,0.015217,0.042,0.002333,62.0,2.7,0.062160,51.70,0.026508,0.206174
682,13,33186,1990,11,11.86,32.31,0.059111,0.036355,0.015217,0.016,0.005000,52.0,2.6,0.050512,52.50,0.051572,0.110683
683,13,33218,1990,12,8.32,32.18,0.105000,0.050355,0.015217,0.044,0.003000,5.0,2.9,0.012432,42.40,0.065572,0.170572

3c) Coluna "tempo" como composição de mês e ano

In [66]:
# Datetime é o jeito "certo" de armazenar datas no pandas
df["tempo"] = pd.to_datetime(dict(year=df["ano"], month=df["mês"], day=1)).dt.to_period("M")
df

,localidade,dia juliano,ano,mês,TMP_CD,SAL_PSU,NH4_MGN,NO3_MGN,NO2_MGN,PT_MGP,PO4_MGP,DQO,DBO,CHLA_MGC,FLR,NOx,Ntot,tempo
0,1,31519,1986,4,11.86,33.70,0.132222,0.045161,0.015217,0.100,0.000000,44.0,5.0,0.265776,26.60,0.060379,0.192601,1986-04
1,1,31548,1986,5,20.32,30.86,0.077780,0.045161,0.015217,0.100,0.000000,51.0,5.0,0.197008,20.40,0.060379,0.138159,1986-05
2,1,31576,1986,6,20.25,29.60,0.217778,0.000000,0.015217,0.370,0.040000,26.0,5.0,0.007840,16.80,0.015217,0.232995,1986-06
3,1,31607,1986,7,23.47,32.33,0.140000,0.045161,0.030435,0.100,0.000000,33.0,5.0,0.255136,29.11,0.075596,0.215596,1986-07
4,1,31637,1986,8,27.08,33.55,0.093333,0.022581,0.030435,0.180,0.000000,43.0,3.2,0.154112,20.20,0.053015,0.146349,1986-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,13,33098,1990,8,25.72,34.57,0.224000,0.011290,0.015217,0.600,0.019333,6.0,2.9,0.316848,77.60,0.026508,0.250508,1990-08
680,13,33127,1990,9,23.08,34.72,0.192889,0.011290,0.015217,0.100,0.025333,29.0,1.9,0.073808,66.80,0.026508,0.219397,1990-09
681,13,33157,1990,10,18.74,32.82,0.179667,0.011290,0.015217,0.042,0.002333,62.0,2.7,0.062160,51.70,0.026508,0.206174,1990-10
682,13,33186,1990,11,11.86,32.31,0.059111,0.036355,0.015217,0.016,0.005000,52.0,2.6,0.050512,52.50,0.051572,0.110683,1990-11
683,13,33218,1990,12,8.32,32.18,0.105000,0.050355,0.015217,0.044,0.003000,5.0,2.9,0.012432,42.40,0.065572,0.170572,1990-12

3d) Variável estação a partir do mês (dez-jan-fev : verão)

In [69]:
estacoes = {
    6: 'inverno',   7: 'inverno',   8: 'inverno',
    9: 'primavera', 10: 'primavera', 11: 'primavera',
    12: 'verão',    1: 'verão',     2: 'verão',
    3: 'outono',    4: 'outono',    5: 'outono',
}

df['estacao'] = df['mês'].map(estacoes)
df

,localidade,dia juliano,ano,mês,TMP_CD,SAL_PSU,NH4_MGN,NO3_MGN,NO2_MGN,PT_MGP,PO4_MGP,DQO,DBO,CHLA_MGC,FLR,NOx,Ntot,tempo,estacao
0,1,31519,1986,4,11.86,33.70,0.132222,0.045161,0.015217,0.100,0.000000,44.0,5.0,0.265776,26.60,0.060379,0.192601,1986-04,outono
1,1,31548,1986,5,20.32,30.86,0.077780,0.045161,0.015217,0.100,0.000000,51.0,5.0,0.197008,20.40,0.060379,0.138159,1986-05,outono
2,1,31576,1986,6,20.25,29.60,0.217778,0.000000,0.015217,0.370,0.040000,26.0,5.0,0.007840,16.80,0.015217,0.232995,1986-06,inverno
3,1,31607,1986,7,23.47,32.33,0.140000,0.045161,0.030435,0.100,0.000000,33.0,5.0,0.255136,29.11,0.075596,0.215596,1986-07,inverno
4,1,31637,1986,8,27.08,33.55,0.093333,0.022581,0.030435,0.180,0.000000,43.0,3.2,0.154112,20.20,0.053015,0.146349,1986-08,inverno
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,13,33098,1990,8,25.72,34.57,0.224000,0.011290,0.015217,0.600,0.019333,6.0,2.9,0.316848,77.60,0.026508,0.250508,1990-08,inverno
680,13,33127,1990,9,23.08,34.72,0.192889,0.011290,0.015217,0.100,0.025333,29.0,1.9,0.073808,66.80,0.026508,0.219397,1990-09,primavera
681,13,33157,1990,10,18.74,32.82,0.179667,0.011290,0.015217,0.042,0.002333,62.0,2.7,0.062160,51.70,0.026508,0.206174,1990-10,primavera
682,13,33186,1990,11,11.86,32.31,0.059111,0.036355,0.015217,0.016,0.005000,52.0,2.6,0.050512,52.50,0.051572,0.110683,1990-11,primavera
683,13,33218,1990,12,8.32,32.18,0.105000,0.050355,0.015217,0.044,0.003000,5.0,2.9,0.012432,42.40,0.065572,0.170572,1990-12,verão

3e) variável indicador como função seletora de pelo menos duas variáveis  
????

In [71]:
# transformando os zeros em NaN novamente

df[colunas_numericas] = df[colunas_numericas].replace(0, np.nan)
df

,localidade,dia juliano,ano,mês,TMP_CD,SAL_PSU,NH4_MGN,NO3_MGN,NO2_MGN,PT_MGP,PO4_MGP,DQO,DBO,CHLA_MGC,FLR,NOx,Ntot,tempo,estacao
0,1,31519,1986,4,11.86,33.70,0.132222,0.045161,0.015217,0.100,NaN,44.0,5.0,0.265776,26.60,0.060379,0.192601,1986-04,outono
1,1,31548,1986,5,20.32,30.86,0.077780,0.045161,0.015217,0.100,NaN,51.0,5.0,0.197008,20.40,0.060379,0.138159,1986-05,outono
2,1,31576,1986,6,20.25,29.60,0.217778,NaN,0.015217,0.370,0.040000,26.0,5.0,0.007840,16.80,0.015217,0.232995,1986-06,inverno
3,1,31607,1986,7,23.47,32.33,0.140000,0.045161,0.030435,0.100,NaN,33.0,5.0,0.255136,29.11,0.075596,0.215596,1986-07,inverno
4,1,31637,1986,8,27.08,33.55,0.093333,0.022581,0.030435,0.180,NaN,43.0,3.2,0.154112,20.20,0.053015,0.146349,1986-08,inverno
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,13,33098,1990,8,25.72,34.57,0.224000,0.011290,0.015217,0.600,0.019333,6.0,2.9,0.316848,77.60,0.026508,0.250508,1990-08,inverno
680,13,33127,1990,9,23.08,34.72,0.192889,0.011290,0.015217,0.100,0.025333,29.0,1.9,0.073808,66.80,0.026508,0.219397,1990-09,primavera
681,13,33157,1990,10,18.74,32.82,0.179667,0.011290,0.015217,0.042,0.002333,62.0,2.7,0.062160,51.70,0.026508,0.206174,1990-10,primavera
682,13,33186,1990,11,11.86,32.31,0.059111,0.036355,0.015217,0.016,0.005000,52.0,2.6,0.050512,52.50,0.051572,0.110683,1990-11,primavera
683,13,33218,1990,12,8.32,32.18,0.105000,0.050355,0.015217,0.044,0.003000,5.0,2.9,0.012432,42.40,0.065572,0.170572,1990-12,verão

# 2. Grupo 3: NH4 e NOx